name: OpenWrt Builder

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  REPO_URL: https://github.com/xiangfeidexiaohuo/EasyWrt
  REPO_BRANCH: main
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        # 確保 Clone 到當前目錄嘅 openwrt 資料夾
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Add PassWall 2 Feeds
      run: |
        # 使用絕對路徑確保指令執行成功
        cd openwrt
        echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall;main' >> feeds.conf.default
        echo 'src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages;main' >> feeds.conf.default
        
        # 執行 update 之前檢查文件是否存在
        if [ -f "./scripts/feeds" ]; then
            ./scripts/feeds update -a
            ./scripts/feeds install -a
        else
            echo "Error: Cannot find ./scripts/feeds. Clone might have failed."
            exit 1
        fi

    - name: Inject Custom Configuration
      run: |
        cd openwrt
        # 修改 IP
        sed -i 's/192.168.1.1/192.168.6.1/g' package/base-files/files/bin/config_generate
        
        # 寫入配置 (CT3003 專用)
        cat >> .config <<EOF
        CONFIG_TARGET_mediatek=y
        CONFIG_TARGET_mediatek_filogic=y
        CONFIG_TARGET_mediatek_filogic_DEVICE_cetron_ct3003=y
        CONFIG_PACKAGE_luci-app-ssr-plus=y
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y
        CONFIG_PACKAGE_luci-app-passwall=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
        CONFIG_LUCI_LANG_zh_Hans=y
        EOF
        
        # 補全依賴
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: github.event.inputs.ssh == 'true'

    - name: Final Compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
